/*DROP DATABASE acidentes_prf;

CREATE DATABASE ACIDENTES_PRF;*/

USE ACIDENTES_PRF;
/*
CREATE TABLE DADOS_ACIDENTES(
id VARCHAR(60),
pesid VARCHAR(10),
data_inversa VARCHAR(10),
dia_semana VARCHAR(30),
horario VARCHAR(20),
uf VARCHAR(10),
br VARCHAR(8),
km VARCHAR(6),
municipio VARCHAR(60),
causa_acidente VARCHAR(80),
tipo_acidente VARCHAR(50) ,
classificacao_acidente VARCHAR(30),
fase_dia VARCHAR(20),
sentido_via VARCHAR(30),
condicao_metereologica VARCHAR(30),
tipo_pista VARCHAR(30),
tracado_via VARCHAR(30),
uso_solo VARCHAR(10),
id_veiculo VARCHAR(6),
tipo_veiculo VARCHAR(30),
marca VARCHAR(40),
ano_fabricacao_veiculo VARCHAR(30),
tipo_envolvido VARCHAR(50),
estado_fisico VARCHAR(30),
idade VARCHAR(50),
sexo VARCHAR(15),
ilesos VARCHAR(10),
feridos_leves VARCHAR(2),
feridos_graves VARCHAR(2),
mortos VARCHAR(2),
latitude VARCHAR(35),
longitude VARCHAR(35),
regional VARCHAR(30),
delegacia VARCHAR(30),
uop VARCHAR(30)
);

LOAD DATA INFILE 'D:/Anna Carolina/Desktop/DADOS ATUALIZADOS TCC/files/acidentes2017.csv'
INTO TABLE DADOS_ACIDENTES
FIELDS TERMINATED by ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'D:/Anna Carolina/Desktop/DADOS ATUALIZADOS TCC/files/acidentes2018.csv'
INTO TABLE DADOS_ACIDENTES
FIELDS TERMINATED by ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'D:/Anna Carolina/Desktop/DADOS ATUALIZADOS TCC/files/acidentes2019.csv'
INTO TABLE DADOS_ACIDENTES
FIELDS TERMINATED by ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'D:/Anna Carolina/Desktop/DADOS ATUALIZADOS TCC/files/acidentes2020.csv'
INTO TABLE DADOS_ACIDENTES
FIELDS TERMINATED by ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

LOAD DATA INFILE 'D:/Anna Carolina/Desktop/DADOS ATUALIZADOS TCC/files/acidentes2021.csv'
INTO TABLE DADOS_ACIDENTES
FIELDS TERMINATED by ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
*/
/*EXCLUINDO COLUNAS QUE NÃO SERÃO UTILIZADAS*/
/*ALTER TABLE DADOS_ACIDENTES DROP COLUMN pesid;
ALTER TABLE DADOS_ACIDENTES DROP COLUMN id_veiculo;
ALTER TABLE DADOS_ACIDENTES DROP COLUMN marca;
ALTER TABLE DADOS_ACIDENTES DROP COLUMN ano_fabricacao_veiculo;
ALTER TABLE DADOS_ACIDENTES DROP COLUMN regional;
ALTER TABLE DADOS_ACIDENTES DROP COLUMN delegacia;
ALTER TABLE DADOS_ACIDENTES DROP COLUMN uop;*/

/*Tirando registros onde idade é maior que 100*/
/*DELETE FROM DADOS_ACIDENTES 
WHERE idade >= 100;*/

/*Tirando registros onde o envolvido é condutor e a idade é menor 12*/
/*DELETE FROM DADOS_ACIDENTES 
WHERE TIPO_ENVOLVIDO = 'CONDUTOR' AND IDADE <= 12;*/

/*Media da Idade para substituir os valores com NA pois são relevantes*/
/*SELECT AVG(IDADE) FROM DADOS_ACIDENTES
WHERE DATA_INVERSA LIKE "%2017";*/

/*SELECT AVG(IDADE) FROM DADOS_ACIDENTES
WHERE DATA_INVERSA LIKE "%2018";*/

/*SELECT AVG(IDADE) FROM DADOS_ACIDENTES
WHERE DATA_INVERSA LIKE "%2019";*/

/*SELECT AVG(IDADE) FROM DADOS_ACIDENTES
WHERE DATA_INVERSA LIKE "%2020";*/

/*SELECT AVG(IDADE) FROM DADOS_ACIDENTES
WHERE DATA_INVERSA LIKE "%2021";*/

/*ATUALIZANDO AS IDADES COM NA COM A MEDIA DAS IDADES*/
/*UPDATE DADOS_ACIDENTES
SET IDADE = '36'
WHERE IDADE = 'NA' AND DATA_INVERSA LIKE "%2017";

UPDATE DADOS_ACIDENTES
SET IDADE = '36'
WHERE IDADE = 'NA' AND DATA_INVERSA LIKE "%2018";

UPDATE DADOS_ACIDENTES
SET IDADE = '36'
WHERE IDADE = 'NA' AND DATA_INVERSA LIKE "%2019";

UPDATE DADOS_ACIDENTES
SET IDADE = '36'
WHERE IDADE = 'NA' AND DATA_INVERSA LIKE "%2020";

UPDATE DADOS_ACIDENTES
SET IDADE = '37'
WHERE IDADE = 'NA' AND DATA_INVERSA LIKE "%2021";*/